version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    # uncomment for docker in docker
#    privileged: true
    restart: always
    volumes:
        # enable persistent volume (warning: make sure that the local jenkins_home folder is created) with 1000 permissions
        - /var/jenkins_home:/var/jenkins_home
        # mount docker sock and binary for docker in docker (only works on linux)
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
